# Dependencies
markdown:         kramdown
redcarpet:
 extensions: ["fenced_code_blocks", "autolink", "tables"]

highlighter: rouge



# Permalinks
permalink:        pretty

# Setup
title:            Tabula Capitolina
tagline:          'In a digital context'
description:      'A site to host a DH project for Tufts DH masters'
#baseurl: https://brclar15.github.io/tabCap/
baseurl: ""


author:
  name:           'Brian Clark'


paginate:         5



links:
  - title: Home
    url: /https://brclar15.github.io/tabCap/
  - title: Intro
    url: /intro
  - title: Photography
    url: /images
  - title: Timelines
    url: timeLinePage
  - title: Timelines
    url: timeLinePage

theme: jekyll-theme-minimal