

# Permalinks
permalink:        pretty

# Setup
title:            "Hyde theme in Jekyll"
tagline:          ''
description:      ''







links:
  - title: Home
    url: /https://brclar15.github.io/tabCap/
  - title: Intro
    url: /intro
  - title: Photography
    url: /images
  - title: Timelines
    url: timeLinePage
  - title: Timelines
    url: timeLinePage
    external: true
